# Generated by Django 5.0 on 2023-12-11 16:01

import measurement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=measurement.models.upload_to),
        ),
    ]
